#! /usr/bin/python

text = "gycyicky s xcicqhctgi.tckgcwgdzcqcds kkzcfg.tc .tfilyck bkci.cgse scugsikckgcr clkqkilkiwqffzcs f jq.kcugsckyilckqlpcq.ecyqj cky cdsgd scf kk sceilksirmkig.xky l cqs ckngcguchzcuqjgsik cv .cpgq.lcugscdsgtsqhh slxczgmcwq.cui.echgs cqkcky wge f llwge xwghxc .ogzxuislkcg. xcqc.gjiw clkmei ecky coqjqchqlk slcwge cq.ecqegdk ecky chqlk slclkzf ckgcq.c bqwki.tce ts  xky ce lit.cdqkk s.lc hdfgz ecky c.qhi.tcwg.j .kig.lcugscjqsiqrf lcky c.mhr scguldqw lcml eckgci.e .kc qwyc. lk ecrfgwpxc j .cky cwghh .klcn s cnsikk .ci.cq.ihds llij cihikqkig.cgucky chqlk slcgn.cjgiw xcemsi.tcyilc. bkcwge cs ji ncky .gjiw cnqlclmsdsil eckgcui.ecky coqjqchqlk scks h .egmlfzceildf ql excrmkchqlk scdsgk lk ecky clkme .kxicyqj cugffgn eczgmsc bqhdf cegn.ckgcky cui.qfcl hiwgfg.xcl  cy s cilcqcmkifikzwfqllczgmcnsgk cg.fzcfqlkchg.kyxcilcikc.gkcqlcfip ckgchzcgn.cwge cqlckngc ttlusghcky clqh cwfmkwyxcq.ecky s i.cfi lcky cdsgrf hclwgnf ecky chqlk sxcz lk seqzcicnqlcqcuggfky cn  pcr ugs cq.cieigkcq.ecfqlkchg.kycq.cihr wif xceg.kclygnch cwge cichitykyqj cnsikk .cz lk seqzxclygnch cwge cqlcicniffcnsik cikckghgssgnxl wg.ecg. xcky c.m.clqkgmcqddsgqwy echqlk scpqihmcq.eclqiechzchqlk scldgp cgucquislkchq.ksqcnyiwychmlkctmie cky ckygmtyklcguck hdf ce j fgd slcqkcqffckih lxcnyqkcilckyilchq.ksqxpqihmcq.ln s ecicws qk xcky c ll .w cguce j fgd sc.qkms cilckgcr cqfnqzlci.cky dsgw llcgucws qkig.cny .cg. cilcqkcqcp zrgqsexclqkgmcqswy ecq.c z rsgnclmldiwigmlfzq.ecqlp eciucich s fzcuibce u wklcnyqkcqhcicws qki.txcpqihmcq.ln s ecyqshg.zxlqkgmcqlp eciucics uqwkgscz kcds l sj cr yqjigscnyqkcqhcicws qki.txpqihmcq.ln s ecgse sxlqkgmcqlp eciucice f k cq.cm.ml ecdsgo wkcnyqkcqhcicws qki.txpqihmcq.ln s eceilpcldqw xlqkgmcqlp eciucicegc.gkyi.tcrmkcrsgnl cky cn rcnyqkcqhcicws qki.txpqihmcq.ln s echill ece qefi. lcq.ecqcogrcgd .i.txkyqkcilcqffxcwg.tsqkmfqkig.lcg.cqcogrcn ffceg."

number_of_dots = text.count('.')
number_of_spaces = text.count(' ')

print("NUMBER OF DOTS {}".format(number_of_dots))
print("NUMBER OF SPACES {}".format(number_of_spaces))

text = text.replace('.', 'N')
text = text.replace(' ', 'E')
text = text.replace('l', 'S')
text = text.replace('k', 'T')
text = text.replace('q', 'A')
text = text.replace('c', ' ')
text = text.replace('g', 'O')
text = text.replace('y', 'H')
text = text.replace('i', 'I')
text = text.replace('s', 'R')
text = text.replace('x', '.')
text = text.replace('h', 'M')
text = text.replace('e', 'D')
text = text.replace('f', 'L')
text = text.replace('t', 'G')
text = text.replace('b', 'X')
text = text.replace('o', 'J')
text = text.replace('r', 'B')
text = text.replace('n', 'W')
text = text.replace('w', 'C')
text = text.replace('m', 'U')
text = text.replace('j', 'V')
text = text.replace('u', 'F')
text = text.replace('z', 'Y')
text = text.replace('d', 'P')
text = text.replace('p', 'K')
text = text.replace('a', 'Q')
text = text.replace('v', 'Z')

print("ASTA E TEXTUL MODIFICAT")
print(text)
